spring:
  application:
    name: docker-test-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/viktar-lebedzeu/spring-config-repo
#          uri: https://github.com/spring-cloud-samples/config-repo.git
          skipSslValidation: true
          force-pull: true
          searchPaths: '{application}'

server:
  port: 9000
