spring:
  application:
    name: docker-test-server
  mustache:
    check-template-location: false

server:
  port: 8100

application:
  groupId: ${project.groupId}
  name: ${project.artifactId}
  version: ${project.version}
  description: ${project.description}
