spring:
  application:
    name: docker-test-server

server:
  port: 8100

application:
  groupId: ${project.groupId}
  name: ${project.artifactId}
  version: ${project.version}
  description: ${project.description}

eureka:
  instance:
    hostname: docker-test-eureka-service
    nonSecurePort: 8761
    preferIpAddress: true
    statusPageUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/health
    homePageUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/eureka}
