spring:
  application:
    name: docker-test-server

server:
  port: 8100

application:
  groupId: ${project.groupId}
  name: ${project.artifactId}
  version: ${project.version}
  description: ${project.description}

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    statusPageUrl: https://${eureka.instance.hostname}:8761/info
    healthCheckUrl: https://${eureka.instance.hostname}:8761/health
    homePageUrl: https://${eureka.instance.hostname}:8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${eureka.instance.hostname}:8761/eureka}
