spring:
  application:
    name: docker-test-eureka-service

server:
  port: 8761

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
